### PR TITLE
Milestone 7 v2 omniauth

### PR DESCRIPTION
**Pull request by KerronKing**
Good day TSE's. 

All requirements for milestone #7 were completed as required. Thanks in advance for your review.

Cheers!

### CODE REVIEW

**Comment by maelfosso** [comment]
# Changes required

I can't sign in with a real facebook account.

Screenshot from 2019-12-03 06-16-50

Run your project in production mode, set the credentials and try it on your side. Then submit a new code review.
Thanks.

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

**Comment by AndresFMoya** [comment]
Hi @maelfosso. You can test the facebook authentication in production mode in the following link: https://frozen-hamlet-01864.herokuapp.com. Looking to hear your comments!

Best!

**Comment by samgaco** [comment]
Hi, everything is well implemented and I can see it's working, so you can move on :+1: 

------------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

**Comment by samgaco** [comment]
Hi, everything is well implemented and I can see it's working, so you can move on :+1: 

------------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

**Pull request merged**
